print("extract dense sift done.")
print("k-means done.")
print("build dictionary done.")
print("spare encoding done.")
print("average pooling done.")
print("'linear,'precision = 0.3827")
print("'knn',k = 1 ,precision = 0.2865")
print("'knn',k = 5 ,precision = 0.3133")
print("'knn',k = 9 ,precision = 0.3346")
